# Original
# equirectangular_node:
#   ros__parameters:
#     cx_offset: 0.0
#     cy_offset: 0.0
#     crop_size: 1920
#     translation: [0.0, 0.0, 0.0]
#     rotation_deg: [0.0, 0.0, 0.0]
#     gpu: True
#     out_width: 3840
#     out_height: 1920

# いったん完成
# equirectangular_node:
#   ros__parameters:
#     cx_offset: 0.0
#     cy_offset: 0.0
#     crop_size: 1355
#     translation: [0.0, 0.0, 0.0]
#     rotation_deg: [0.0, 0.0, 0.0]
#     gpu: True
#     out_width: 1920
#     out_height: 960
#     # トリミングしない場合は crop_y をコメントアウト
#     crop_y: [150, 750] # [y_min, y_max] e.g. [400, 1500]

# same theta_s resolution
equirectangular_node:
  ros__parameters:
    cx_offset: 0.0
    cy_offset: 0.0
    crop_size: 1355
    translation: [0.0, 0.0, 0.0]
    rotation_deg: [0.0, 0.0, 0.0]
    gpu: true
    out_width: 1280
    out_height: 640
    # トリミングしない場合は crop_y をコメントアウト
    crop_y: [145, 475] # [y_min, y_max] e.g. [400, 1500]
